namespace Altoholic.Models
{
    public class PlayerCurrencies
    {
        public int Achievement_Certificate { get; set; }
        public int Allagan_Tomestone_Of_Aesthetics { get; set; }
        public int Allagan_Tomestone_Of_Allegory { get; set; }
        public int Allagan_Tomestone_Of_Aphorism { get; set; }
        public int Allagan_Tomestone_Of_Astronomy { get; set; }
        public int Allagan_Tomestone_Of_Causality { get; set; }
        public int Allagan_Tomestone_Of_Comedy { get; set; }
        public int Allagan_Tomestone_Of_Creation { get; set; }
        public int Allagan_Tomestone_Of_Esoterics { get; set; }
        public int Allagan_Tomestone_Of_Genesis { get; set; }
        public int Allagan_Tomestone_Of_Goetia { get; set; }
        public int Allagan_Tomestone_Of_Heliometry { get; set; }
        public int Allagan_Tomestone_Of_Law { get; set; }
        public int Allagan_Tomestone_Of_Lore { get; set; }
        public int Allagan_Tomestone_Of_Mathematics { get; set; }
        public int Allagan_Tomestone_Of_Mendacity { get; set; }
        public int Allagan_Tomestone_Of_Mythology { get; set; }
        public int Allagan_Tomestone_Of_Phantasmagoria { get; set; }
        public int Allagan_Tomestone_Of_Philosophy { get; set; }
        public int Allagan_Tomestone_Of_Poetics { get; set; }
        public int Allagan_Tomestone_Of_Revelation { get; set; }
        public int Allagan_Tomestone_Of_Scripture { get; set; }
        public int Allagan_Tomestone_Of_Soldiery { get; set; }
        public int Allagan_Tomestone_Of_Verity { get; set; }
        public int Allied_Seal { get; set; }
        public int Ananta_Dreamstaff { get; set; }
        public int Arkasodara_Pana { get; set; }
        public int Bicolor_Gemstone { get; set; }
        public int Black_Copper_Gil { get; set; }
        public int Bozjan_Cluster { get; set; }
        public int Carved_Kupo_Nut { get; set; }
        public int Centurio_Seal { get; set; }
        public int Cosmocredit { get; set; }
        public int Earth_Cluster { get; set; }
        public int Earth_Crystal { get; set; }
        public int Earth_Shard { get; set; }
        public int Fae_Fancy { get; set; }
        public int Faux_Leaf { get; set; }
        public int Felicitous_Token { get; set; }
        public int Fire_Cluster { get; set; }
        public int Fire_Crystal { get; set; }
        public int Fire_Shard { get; set; }
        public int Flame_Seal { get; set; }
        public int Gil { get; set; }
        public int Hammered_Frogment { get; set; }
        public int Ice_Cluster { get; set; }
        public int Ice_Crystal { get; set; }
        public int Ice_Shard { get; set; }
        public int Irregular_Tomestone_Of_Creation { get; set; }
        public int Irregular_Tomestone_Of_Esoterics { get; set; }
        public int Irregular_Tomestone_Of_Genesis_i { get; set; }
        public int Irregular_Tomestone_Of_Genesis_ii { get; set; }
        public int Irregular_Tomestone_Of_Goetia { get; set; }
        public int Irregular_Tomestone_Of_Law { get; set; }
        public int Irregular_Tomestone_Of_Lore { get; set; }
        public int Irregular_Tomestone_Of_Mendacity { get; set; }
        public int Irregular_Tomestone_Of_Mythology { get; set; }
        public int Irregular_Tomestone_Of_Pageantry { get; set; }
        public int Irregular_Tomestone_Of_Phantasmagoria { get; set; }
        public int Irregular_Tomestone_Of_Philosophy { get; set; }
        public int Irregular_Tomestone_Of_Scripture { get; set; }
        public int Irregular_Tomestone_Of_Soldiery { get; set; }
        public int Irregular_Tomestone_Of_Tenfold_pageantry { get; set; }
        public int Irregular_Tomestone_Of_Verity { get; set; }
        public int Islanders_Cowrie { get; set; }
        public int Ixali_Oaknot { get; set; }
        public int Kojin_Sango { get; set; }
        public int Lightning_Cluster { get; set; }
        public int Lightning_Crystal { get; set; }
        public int Lightning_Shard { get; set; }
        public int Loporrit_Carat {  get; set; }
        public int Lunar_Credit {  get; set; }
        public int Mamool_Ja_Nanook { get; set; }
        public int MGF { get; set; }
        public int MGP { get; set; }
        public int Namazu_Koban { get; set; }
        public int Omicron_Omnitoken { get; set; }
        public int Orange_Crafters_Scrip { get; set; }
        public int Orange_Gatherers_Scrip { get; set; }
        public int Pelu_Pelplume { get; set; }
        public int Purple_Crafters_Scrip { get; set; }
        public int Purple_Gatherers_Scrip { get; set; }
        public int Qitari_Compliment { get; set; }
        public int Rainbowtide_Psashp { get; set; } 
        public int Sack_of_Nuts { get; set; }
        public int Seafarers_Cowrie { get; set; }
        public int Serpent_Seal { get; set; }
        public int Skybuilders_Scrip { get; set; }
        public int Steel_Amaljok { get; set; }
        public int Storm_Seal { get; set; }
        public int Sylphic_Goldleaf { get; set; }
        public int Titan_Cobaltpiece { get; set; }
        public int Trophy_Crystal { get; set; }
        public int Vanu_Whitebone { get; set; }
        public int Venture { get; set; }
        public int Water_Cluster { get; set; }
        public int Water_Crystal { get; set; }
        public int Water_Shard { get; set; }
        public int White_Crafters_Scrip { get; set; }
        public int White_Gatherers_Scrip { get; set; }
        public int Wind_Cluster { get; set; }
        public int Wind_Crystal { get; set; }
        public int Wind_Shard { get; set; }
        public int Wolf_Mark { get; set; }
        public int Yellow_Crafters_Scrip { get; set; }
        public int Yellow_Gatherers_Scrip { get; set; }
        public int Yo_Kai_Legendary_Jibanyan_Medal { get; set; }
        public int Yo_Kai_Legendary_Komasan_Medal { get; set; }
        public int Yo_Kai_Legendary_Whisper_Medal { get; set; }
        public int Yo_Kai_Legendary_Blizzaria_Medal { get; set; }
        public int Yo_Kai_Legendary_Kyubi_Medal { get; set; }
        public int Yo_Kai_Legendary_Komajiro_Medal { get; set; }
        public int Yo_Kai_Legendary_Manjimutt_Medal { get; set; }
        public int Yo_Kai_Legendary_Noko_Medal { get; set; }
        public int Yo_Kai_Legendary_Venoct_Medal { get; set; }
        public int Yo_Kai_Legendary_Shogunyan_Medal { get; set; }
        public int Yo_Kai_Legendary_Hovernyan_Medal { get; set; }
        public int Yo_Kai_Legendary_Robonyan_f_type_Medal { get; set; }
        public int Yo_Kai_Legendary_Usapyon_Medal { get; set; }
        public int Yo_Kai_Legendary_Zazel_Medal { get; set; }
        public int Yo_Kai_Legendary_lord_ananta_Medal { get; set; }
        public int Yo_Kai_Legendary_Lord_enma_Medal { get; set; }
        public int Yo_Kai_Legendary_Damona_Medal { get; set; }
        public int Yo_Kai_Medal { get; set; }
        public int Weekly_Acquired_Tomestone { get; set; }
        public int Weekly_Limit_Tomestone { get; set; }

        /*public override string ToString()
        {
            return string.Format("Name: {0}, Type: {1}, Cost: {2}, UserName: {3}", productName, productType, productCost, userName);
        }*/
    }
}
